### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by manojbadam** [marsanla/sails-elasticsearch#4]
Hi Team,

Im trying to run in node v4.1 and recieving  "Maximum call stack size exceeded" error while trying to initialize the waterline orm, 

It is working fine in older versions (v0.1x)

**Comment by michaek** [comment]
I'm running into the same problem, with many repeated lines like:

```
  at Function.EventEmitter.listenerCount (events.js:399:20)
  at Log.listenerCount (./node_modules/waterline-elasticsearch/node_modules/elasticsearch/src/lib/log.js:68:25)
  at Function.EventEmitter.listenerCount (events.js:399:20)
  at Log.listenerCount (./node_modules/waterline-elasticsearch/node_modules/elasticsearch/src/lib/log.js:68:25)
  at Function.EventEmitter.listenerCount (events.js:399:20)
  at Log.listenerCount (./node_modules/waterline-elasticsearch/node_modules/elasticsearch/src/lib/log.js:68:25)
  at Function.EventEmitter.listenerCount (events.js:399:20)
  at Log.listenerCount (./node_modules/waterline-elasticsearch/node_modules/elasticsearch/src/lib/log.js:68:25)
```

**Comment by michaek** [comment]
It appears this may be fixed by updating the dependency on elasticsearch: https://github.com/elastic/elasticsearch-js/issues/291

**Comment by tielur** [comment]
@michaek I'm running node v4.2.3 and experiencing this issue. What was your fix?

**Comment by Oldwo1f** [comment]
I got the same issue,
Can you explain a bit more where to update dependency on elaticsearch ?

i got this : 
```
curl -XGET 'localhost:9200'  ------->
{
  "name" : "Comet",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.3.1",
    "build_hash" : "bd980929010aef404e7cb0843e61d0665269fc39",
    "build_timestamp" : "2016-04-04T12:25:05Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.0"
  },
  "tagline" : "You Know, for Search"
}
```
```
 node -v   ------>
v5.8.0
```
```
package.json dependencies
"dependencies": {
    "bluebird": "3.3.4",
    "bower": "1.7.7",
    "chai": "3.5.0",
    "ejs": "2.3.4",
    "grunt": "0.4.5",
    "grunt-contrib-clean": "0.6.0",
    "grunt-contrib-coffee": "0.13.0",
    "grunt-contrib-concat": "0.5.1",
    "grunt-contrib-copy": "0.5.0",
    "grunt-contrib-cssmin": "0.9.0",
    "grunt-contrib-jst": "0.6.0",
    "grunt-contrib-less": "1.1.0",
    "grunt-contrib-uglify": "0.7.0",
    "grunt-contrib-watch": "0.5.3",
    "grunt-sails-linker": "~0.10.1",
    "grunt-sync": "0.2.4",
    "include-all": "~0.1.6",
    "kerberos": "0.0.19",
    "lockdown": "0.0.8-dev",
    "nodemailer": "2.3.0",
    "rc": "1.0.1",
    "request": "2.69.0",
    "sails": "~0.12.1",
    "sails-disk": "~0.10.9",
    "sails-elasticsearch": "0.10.3",
    "sails-mongo": "0.12.0",
    "sinon": "1.17.3",
    "waterline-elasticsearch": "0.1.3"
  }
```

Should i install **elasticsearch-js** in my project? Because i do not see it sails-elasticsearch dependencies
